accounts/urls.py
"""Module managing the urls."""
from django.urls import path
from accounts.views import signup, logout_user, login_user, profile

app_name = 'accounts'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('signup/', signup, name='signup'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

billeterieJO/urls.py
"""Module managing the urls."""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ticketing.views import index
from billeterieJO import settings

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('boutique/', include('ticketing.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketing/urls.py
"""Module managing the urls."""
from django.urls import path
from ticketing.views import add_to_cart, cart, create_checkout_session, update_quantities, all_offers

app_name = 'ticketing'

urlpatterns = [
    path('cart/', cart, name="cart"),
    path('cart/update-quantities', update_quantities, name="update-quantities"),
    path('cart/create-checkout-session', create_checkout_session, name="create-checkout-session"),
    path('offers', all_offers, name="all-offers"),
    path('offer/<str:slug>/add-to-cart', add_to_cart, name="add-to-cart"),
]

templates/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Billeterie JO 2024</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" 
        crossorigin="anonymous">
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/3.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    </head>
    <body>
        <div class="container">
            <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
                <a href="{% url 'index' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                    <img src="/media/logo_jo.png" alt="Logo des JOs" style="max-width: 50px">
                </a>

                <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Acceuil</a></li>
                    <li><a href="{% url 'ticketing:all-offers' %}" class="nav-link px-2 link-dark">Les offres</a></li>
                    <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
                    <li><a href="#" class="nav-link px-2 link-dark">A propos</a></li>
                </ul>

                <div class="col-md-3 text-end d-flex align-items-center justify-content-around">
                    {% if user.is_authenticated %}
                        {% if user.cart and not user.cart.ordered and user.cart.orders.count != 0 %}
                            <a href="{% url 'ticketing:cart' %}"><i class="fi fi-rr-shopping-cart"></i> ({{ user.cart.orders.count }})</a>
                        {% endif %}
                        <a href="{% url 'accounts:profile' %}" ><i class="fi fi-rr-user"></i></a>
                        <a href="{% url 'accounts:logout' %}" class="btn btn-primary px-4 me-md-2">Se déconnecter</a>
                    {% else %}
                        <a href="{% url 'accounts:login' %}" class="btn btn-primary px-4 me-md-2">Se connecter</a>
                        <a href="{% url 'accounts:signup' %}"class="btn btn-primary px-4 me-md-2">S'inscrire</a>
                    {% endif %}
                </div>
            </header>
        </div>

    {% block content %}

    {% endblock %}

        <div class="container"> 
            <footer class="py-3 my-4"> 
                <ul class="nav justify-content-center border-bottom pb-3 mb-3"> 
                    <li class="nav-item"><a href="{% url 'index' %}" class="nav-link px-2 text-body-secondary">Acceuil</a></li> 
                    <li class="nav-item"><a href="{% url 'ticketing:all-offers' %}" class="nav-link px-2 text-body-secondary">Les offres</a></li> 
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li> 
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">A propos</a></li> 
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Mentions légales</a></li> 
                </ul> 
                <p class="text-center text-body-secondary">© Jeux olympiques Paris 2024</p> </footer>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" 
        crossorigin="anonymous"></script>
    </body>
</html>