accounts/urls.py
"""Module managing the urls."""
from django.urls import path
from accounts.views import signup, logout_user, login_user, profile

app_name = 'accounts'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('signup/', signup, name='signup'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

billeterieJO/urls.py
"""Module managing the urls."""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ticketing.views import index
from billeterieJO import settings

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('boutique/', include('ticketing.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketing/urls.py
"""Module managing the urls."""
from django.urls import path
from ticketing.views import add_to_cart, cart, create_checkout_session, update_quantities, all_offers

app_name = 'ticketing'

urlpatterns = [
    path('cart/', cart, name="cart"),
    path('cart/update-quantities', update_quantities, name="update-quantities"),
    path('cart/create-checkout-session', create_checkout_session, name="create-checkout-session"),
    path('offers', all_offers, name="all-offers"),
    path('offer/<str:slug>/add-to-cart', add_to_cart, name="add-to-cart"),
]

ticketing/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from billeterieJO.settings import AUTH_USER_MODEL


# Model for the different offers
class Offer(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, blank=True)
    spectator_number = models.IntegerField(default=0)
    price = models.FloatField(default=0.0)
    stock = models.IntegerField(default=0)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return f"{self.name} ({self.stock})"
    
    def get_absolute_url(self):
        return reverse("ticketing:offer", kwargs={"slug": self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.name)
        super().save(*args, **kwargs)
        

# Model for order
class Order(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.offer.name} ({self.quantity})"


# Model for cart containing orders
class Cart(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    orders = models.ManyToManyField(Order)
    total = models.FloatField(default=0.0)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(blank=True,null=True)
    generated_key =models.CharField(max_length=255, default="")
    
    def __str__(self):
        return f"{self.user.email} ({self.total})"
    
    def delete(self, *args, **kwargs):
        for order in self.orders.all():
            order.ordered = True
            order.ordered_date = timezone.now()
            order.save()
            
        self.orders.clear()
        super().delete(*args, **kwargs)

ticketing/forms.py
from django import forms

from ticketing.models import Order

class OrderForm(forms.ModelForm):
    quantity = forms.ChoiceField(choices=[(i, i) for i in range(1,11)])
    delete = forms.BooleanField(initial=False, required=False, label="Supprimer")
    
    class Meta:
        model = Order
        fields = ["quantity"]
        
    def save(self, *args, **kwargs):
        if self.cleaned_data["delete"]:
            return self.instance.delete()
            
        return super().save(*args, **kwargs)

ticketing/views.py
from django.http import HttpResponse
from django.forms import modelformset_factory
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from accounts.models import Customer
from ticketing.forms import OrderForm
from ticketing.models import Offer, Cart, Order
from django.utils import timezone
from django.contrib.auth.decorators import login_required

def index(request):
    offers = Offer.objects.all()
    
    return render(request, 'ticketing/index.html', context={"offers": offers})

def all_offers(request):
    offers = Offer.objects.all()
    return render(request, 'ticketing/offers.html', context={"offers": offers})

def add_to_cart(request, slug):
    user: Customer = request.user
    user.add_to_cart(slug=slug)
    
    return redirect(reverse("ticketing:all-offers"))

@login_required
def cart(request):
    orders = Order.objects.filter(user=request.user)
    if orders.count() == 0:
        return redirect('index')
    # extra = 0 to prevent adding new form for new product
    OrderFormSet = modelformset_factory(Order, form=OrderForm, extra=0)
    formset = OrderFormSet(queryset=orders)
    
    return render(request, 'ticketing/cart.html', context={"forms":formset})

def update_quantities(request):
    OrderFormSet = modelformset_factory(Order, form=OrderForm, extra=0)
    formset = OrderFormSet(request.POST, queryset=Order.objects.filter(user=request.user))
    if formset.is_valid():
        formset.save()
        
    return redirect('ticketing:cart')
    
def create_checkout_session(request):
    # renomme avec payed
    cart = get_object_or_404(Cart, user=request.user)
    cart.ordered = True
    cart.ordered_date = timezone.now()
    cart.save()
    
    return render(request, 'ticketing/payment.html')

ticketing/templates/ticketing/cart.html
{% extends "base.html" %}

{% block content %}
    <div class="container d-flex flex-column justify-content-evenly">
        <form method="POST" action="{% url 'ticketing:update-quantities' %}">
            {% csrf_token %}
            {% comment %} needed for django {% endcomment %}
            {{ forms.management_form }}
            {% for form in forms %}
                <div>
                    <h2>{{ form.instance.offer.name }}</h2>
                    <p>{{ form.instance.offer.description}}</p>
                    {{ form.as_p }}
                </div>
            {% endfor%}
            <button class="btn btn-primary btn-lg px-4 me-md-2" type="submit">Mettre à jour les quantités</button>
        </form>
    
    
        {% comment %} it will direct to stripe payment interface {% endcomment %}
        <form action="{% url 'ticketing:create-checkout-session' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-primary btn-lg px-4 me-md-2 m-4" type="submit">Procéder au paiement</button>
        </form>
    </div>

{% endblock %}

ticketing/templates/ticketing/index.html
{% extends "base.html" %}

{% block content %}
    <main>

        <div class="container col-xxl-8 px-4 py-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                <div class="col-10 col-sm-8 col-lg-6">
                    {% load static %}
                    <img src="{% static 'image/paris.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                </div>
                <div class="col-lg-6">
                    <h1 class="display-5 fw-bold lh-1 mb-3">Paris acceuille les Jeux olympiques 2024!</h1>
                    <p class="lead">La ville Lumière a la chance et l'honneur d'acceuillir les Jeux olympiques et paralympiques de 2024. Vous pourrez trouver sur ce site différentes offres vous permettant d'accèder aux épreuves.</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href="{% url 'ticketing:all-offers' %}" class="btn btn-primary btn-lg px-4 me-md-2">Accéder aux offres</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <h2>Qu'est ce que les Jeux olympiques ?</h2>
            <p>
                Les Jeux olympiques d'été c'est avant tout une compétition sportive rassemblant les payx du monde entier.
                Ces jeux se déroulent tous les 4 ans et le pays hôte change pour chaque édition.
                La création du format que l'on connait de ces jeux remontent en 1896 à Athènes mais leur origine est bien plus ancienne : la Grèce antique.
            </p>
        </div>

        <div class="container">
            <h2>Ce qui vous attend pour cette édition:</h2>
            <ul>
                <li>Des épreuves tous les jours pendant une 15 jours</li>
                <li>Des animations dans divers lieux</li>
                <li>Des épreuves se déroulant sur tout le territoire français</li>
            </ul>
        </div>

        <div class="container">
            <h2>Quelles épreuves pourrez vous retrouver ?</h2>
            <div class="d-flex justify-content-between">
                <div class="card" style="width: 18rem;">
                    {% load static %}
                    <img src="{% static 'image/volleyball.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                        <div class="card-body">
                            <h5 class="card-title">Volley-ball</h5>
                            <p class="card-text">Sport collectif qui oppose 2 équipes de 6 personnes. Ces équipes sont séparés par un filet et un match peut durer de 1h à 1h30.</p>
                        </div>
                </div>
                <div class="card" style="width: 18rem;">
                    {% load static %}
                    <img src="{% static 'image/escrime.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">L'escrime</h5>
                        <p class="card-text">Sport de combat qui oppose 2 athlètes devant effectuer des touches à l'aide d'un fleuret. Le but étant d'effectuer 15 touches pour l'emporter.</p>
                    </div>
                </div>
                <div class="card" style="width: 18rem;">
                    {% load static %}
                    <img src="{% static 'image/athletisme.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">L'athlétisme</h5>
                        <p class="card-text">Sport incontournable des JO, l'athlétisme comprend en réalité un ensemble d'épreuves sportives telles que le saut, la course...</p>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

ticketing/templates/ticketing/offers.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Les offres</h1>
            <p class="fs-5 text-muted">Différentes offres vous sont proposées afin de pouvoir accéder aux épreuves. Chaque offre donne accès à un nombre de personne différent afin de pouvoir assister aux épreuves entre amis ou en famille. N'attendez plus et faites votre choix, nous avons hâte de vous voir sur les différentes épreuves !</p>
        </div>
    </div>

    <main class="container">
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for offer in offers %}
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h4 class="my-0 fw-normal">{{ offer.name }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ offer.price }}<small class="text-muted fw-light">€</small></h1>
                            <p>{{ offer.description }}</p>
                            {% if user.is_authenticated%}
                                <a href="{% url 'ticketing:add-to-cart' offer.slug %}" class="btn btn-primary px-4 me-md-2">Ajouter au panier</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>

{% endblock %}

ticketing/templates/ticketing/payment.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <h2>Paiement réussit</h2>      
        <a href="{% url 'index' %}">Retourner à l'acceuil</a>
    </div>
{% endblock %}